Support building pgsodium on windows
michelp/pgsodium pull request #72
Opened 2023-02-07 21:40 UTC by andrewwasielewski

This PR adds support to build pgsodium on windows with MSVC.

The primary changes are:
- updating function prototypes with `PGDLLEXPORT `
- adding `pgsodium_getkey.bat` for windows (assumes openssl is installed)
- utilizing `_access` and `fgets` to check the permissions and read the output of the `getkey_script`
- adding solution and project files for VC16 (Visual Studio 2019) in a new `build` directory

2023-02-10 04:10 UTC, Godwottery requested changes
I had a quick look through and made some minor comments. 

If it were my project I would appreciate two pull requests, one that just added PGDLLEXPORT, which can be used by other OSes as well, and then one that adds on the Windows specific parts. That makes it easier to keep apart.

2023-02-10 04:10 UTC, Godwottery commented on src/pgsodium.c
> +	secret_len = 65;   // extra byte for null terminator
This extra byte is necessary since fgets will append a newline. See https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fgets-fgetws?view=msvc-170

Perhaps the comment could be updated to include the source of the newline, which confused me at least. I spent some time digging into the documentation to find out WHY it was included.

2023-02-10 04:10 UTC, Godwottery commented on src/pgsodium.c
> +	secret_buf[strcspn(secret_buf, "\r\n")] = '\0';
This finds the first \r\n and replaces with a single \0. Is this intended. The getkey_script should probably not be returning line endings. 0x0D 0x0A could show up somewhere in the key, and this would then be changed. I think the original version which just checks the last value is more correct.

2023-02-10 12:15 UTC, andrewwasielewski commented on src/pgsodium.c
> +#ifdef WIN32
Thanks for taking the time to review and provide constructive feedback. I agree, using the compiler defined `_WIN32` is more robust

2023-02-10 15:49 UTC, andrewwasielewski commented on src/pgsodium.c
> +#define X_OK 6
Thanks, I agree that write permissions on the `getkey_script` file are not strictly necessary, have amended per your recommendation.

2023-02-10 16:34 UTC, michelp commented
Having not touched a Windows machine for 27 years, I can't really speak to the code, but the changes are minimal and I'm inclined to merge it since the tests pass, but, I think there's one missing piece which is changes to the github action test runner that builds and runs the tests on Windows.  Since I can't personally maintain it I would need that step done to ensure future releases on Windows aren't broken.

2023-02-13 15:58 UTC, andrewwasielewski commented on src/pgsodium.c
> +	if (fgets (secret_buf, (int)secret_len, fp) == NULL)
I like this approach, it's very clean. Thanks for providing the suggestion, would you like me to add you as a co-author on the commit?

```
size_t getline(char** lineptr, size_t* n, FILE* stream)
{
	// We expect 64 bytes, allocate enough to be sure.
	const int BUFFERSIZE = 1024;
	char *buffer = malloc(BUFFERSIZE);
	if (fgets (buffer, BUFFERSIZE-1 , stream) == NULL)
	{
		free(buffer);
		return -1;
	}
	*lineptr = buffer;
	size_t char_read = strlen(*lineptr);
	*n = char_read;
	return char_read;
}
```

2023-02-14 06:21 UTC, Godwottery commented on src/pgsodium.c
> +	if (fgets (secret_buf, (int)secret_len, fp) == NULL)
Happy to let you take the credit. No need to mention me.

2023-02-14 11:26 UTC, Godwottery commented
I looked into building with less requirements, I was particularly trying to get rid of the requirements to install Visual Studio on the build machine. 

The entire project can be built using only cl.exe and the linker. This means it can also be built using msbuild. msbuild is available on the Microsoft homepage: https://visualstudio.microsoft.com/downloads/

I created a simple .proj file (attached as .proj.txt because Github wouldn't let me upload the .proj file inline), and can now build the dll from msbuild directly from the command line.

[pgsodium.proj.txt](https://github.com/michelp/pgsodium/files/10731805/pgsodium.proj.txt)

msbuild pgsodium.proj /p:libsodiumLocation="..Downloads\libsodium-1.0.18-stable-msvc\libsodium" /p:PostgreSQLLocation="C:\ProgramFiles\PostgreSQL\15"/p:Platform=x64 /p:Configuration=Release

I think this would be a simpler solution: there are less Windows specific files (only 1), the dependencies are smaller (msbuild < Visual Studio). The parametrization is also done on the command line, so the Windows readme can be simplified.

2023-02-15 08:51 UTC, Godwottery commented
Built a dll using msbuild with the pgsodium.proj file only. Running that dll. Thus we can remove two of the three WIndows specific files, leaving only a simple build project (and perhaps the readme)

2023-02-16 21:48 UTC, andrewwasielewski commented
@Godwottery Thanks for assembling the project file for msbuild. It works quite nicely and removes the manual steps required. I'm looking into creating a windows test runner with it.

2023-03-03 14:12 UTC, andrewwasielewski commented
@michelp I've added a github actions test runner which builds and runs the unit tests on windows. Currently, the windows unit tests do not pass, however, the windows test output aligns with the linux test output (linux failure may possibly be masked since it's run inside a container?)

@Godwottery Thanks for all your input! Just checking to see if you have any further feedback? Would you like to mark our conversations as resolved, or should I do that?

2023-03-09 08:49 UTC, Godwottery commented
> @Godwottery Thanks for all your input! Just checking to see if you have any further feedback? Would you like to mark our conversations as resolved, or should I do that?
I have no further feedback at this time. 
Please go ahead and mark our conversations as resolved if you consider them done.

2023-03-28 20:25 UTC, andrewwasielewski commented
@michelp Just checking in to see if you have any further comments or feedback? Thank you

2023-04-04 03:06 UTC, michelp commented
Sorry for the delay, currently in the middle of another project rolling out, and will get to this PR in the next couple of days.  One minor complication may be that recently @ioguix pointed out that the tests don't run properly with psql but should be using pg_prove, so I'm going to try and fix that which will likely mean some small changes to your PR to use pg_prove as well.  Once I have a PR for that I'll ping that back here to make the necessary changes.

2023-05-29 20:35 UTC, michelp commented
Hi @andrewwasielewski , sorry for the long delay!  I just released 3.1.7 that now correctly uses pg_prove to run the tests and thus catches missing failures that were occuring that didn't get caught during debug, if you update to the latest main branch, I'll go through your PR again and merge it, thanks!  Any questions just lmk.

2023-06-01 20:13 UTC, andrewwasielewski commented
> Hi @andrewwasielewski , sorry for the long delay! I just released 3.1.7 that now correctly uses pg_prove to run the tests and thus catches missing failures that were occuring that didn't get caught during debug, if you update to the latest main branch, I'll go through your PR again and merge it, thanks! Any questions just lmk.

Ok, thanks! Will update my PR with the latest changes and test

2023-09-20 01:28 UTC, michelp approved these changes

2023-09-20 01:29 UTC, merged